### ISSUE TITLE
SMS

### ISSUE THREAD

**Issue by qwo** [Code4HR/okcandidate-okcontact#2]
- Replace url with okc.code4hr.org.

-I don't think we need a shortened URL but with SMS its nice to have characters < 140 so lets verify with some test messages we can make that with this copy. 
- I don't believe we collect the surveyors name, only email and phone 

https://github.com/Code4HR/okcandidate-okcontact/blob/master/contact.js#L63

**Comment by MFogleman** [comment]
URL replaced, references to surveryors' names removed.
